# Generated by Django 5.0.2 on 2024-02-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0005_subscribe_id_alter_subscribe_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
