# Generated by Django 5.0.2 on 2024-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0007_alter_subscribe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('icon', models.FileField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('testimonial_description', models.TextField(max_length=255)),
                ('testimonial_author', models.CharField(max_length=255)),
                ('author_description', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(upload_to='media/')),
            ],
        ),
    ]
