# Generated by Django 5.0.2 on 2024-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0008_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='icon_background',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
