# Generated by Django 5.0.2 on 2024-02-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0009_featured_icon_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='icon',
            new_name='icon_logo',
        ),
    ]
