# Generated by Django 5.0.2 on 2024-02-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0010_rename_icon_featured_icon_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_background', models.FileField(upload_to='background/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='business/')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='markating/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('a_description', models.TextField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial/')),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Videoblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video/')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='videoblog/')),
            ],
        ),
        migrations.CreateModel(
            name='Videoresources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video/')),
                ('heding', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('spana', models.CharField(max_length=255)),
            ],
        ),
    ]
