# Generated by Django 5.0.2 on 2024-02-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0012_videoblog_logo_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='designation',
            new_name='p_designation',
        ),
    ]
