# Generated by Django 5.0.2 on 2024-02-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0013_rename_designation_testimonial_p_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='logo',
            field=models.FileField(default=2, upload_to='testi/'),
            preserve_default=False,
        ),
    ]
