# Generated by Django 5.0.2 on 2024-02-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0016_business_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('company_size_choices', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '200-5000')], max_length=128)),
                ('industry_choices', models.CharField(choices=[('1', 'Agriculture'), ('2', 'Banking, Finance'), ('3', 'Business Services & Software')], max_length=128)),
                ('job_role_choices', models.CharField(choices=[('1', 'C-Sute'), ('2', 'VP')], max_length=128)),
                ('country_choices', models.CharField(choices=[('us', 'United States'), ('albania', 'Albania')], max_length=128)),
                ('user', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='featured',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='marketing',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='videoblog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='videoresources',
            options={'ordering': ['id']},
        ),
    ]
