# Generated by Django 5.0.2 on 2024-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0017_contact_alter_business_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('heding', models.CharField(max_length=128)),
                ('logo', models.FileField(upload_to='Footer/')),
                ('icon', models.FileField(upload_to='FooterSection/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_size_choices',
            field=models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '200-500')], max_length=128),
        ),
    ]
