# Generated by Django 5.0.2 on 2024-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0018_footer_alter_contact_company_size_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='heding',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='footer',
            name='icon',
            field=models.FileField(blank=True, upload_to='FooterSection/'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.FileField(blank=True, upload_to='Footer/'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
