# Generated by Django 5.0.2 on 2024-03-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0019_alter_footer_heding_alter_footer_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='heding',
            new_name='decsription',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='logo',
        ),
        migrations.AddField(
            model_name='footer',
            name='icons',
            field=models.FileField(blank=True, upload_to='footersection/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image',
            field=models.FileField(blank=True, upload_to='footer/'),
        ),
    ]
