# Generated by Django 5.0.2 on 2024-03-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0021_footer_hed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
