# Generated by Django 5.0.2 on 2024-03-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0023_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='h1',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
