# Generated by Django 5.0.2 on 2024-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0024_img_h1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.FileField(blank=True, upload_to='afe/'),
        ),
    ]
