# Generated by Django 5.0.2 on 2024-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0026_latest_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_customers',
            name='image',
            field=models.FileField(upload_to='media10/'),
        ),
    ]
