# Generated by Django 5.0.2 on 2024-03-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0027_alter_latest_customers_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latest_customers',
            new_name='Latest_customer',
        ),
    ]
