# Generated by Django 5.0.2 on 2024-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0028_rename_latest_customers_latest_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('hero_image', models.FileField(blank=True, upload_to='media_one/')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('logo', models.FileField(blank=True, upload_to='media20/')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
