# Generated by Django 5.0.2 on 2024-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0029_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
