# Generated by Django 5.0.2 on 2024-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0030_product_background_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='business',
            name='hero_image',
            field=models.FileField(blank=True, upload_to='media_one/'),
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
