# Generated by Django 5.0.2 on 2024-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibbitz1', '0031_delete_product_business_hero_image_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
